#!/bin/bash

## Run PHP Code Sniffer
##
## Usage: ddev phpcs

#ddev-generated

# Load environment variables
if [ -f .ddev/.env-kanopi-wp ]; then
    source .ddev/.env-kanopi-wp
fi

echo "Running PHP Code Sniffer..."

ddev exec composer phpcs