#!/bin/bash

## Run PHP Code Beautifier and Fixer
##
## Usage: phpcbf

#ddev-generated

# Note: This command doesn't require config.kanopi.yaml
# Configuration is handled by composer.json and phpcs.xml

echo "Running PHP Code Beautifier and Fixer..."

ddev exec composer phpcbf