#!/bin/bash

## Description: Run PHP Code Sniffer
## Usage: phpcs
## Example: "ddev phpcs"

#ddev-generated

# Note: This command doesn't require config.kanopi.yaml
# Configuration is handled by composer.json and phpcs.xml

echo "Running PHP Code Sniffer..."

ddev exec composer phpcs