#!/usr/bin/env bash

## Description: Initialize Lefthook.
## Usage: project-lefthook
## Example: "ddev project-lefthook"
## Aliases: project:lefthook

#ddev-generated

# Colors / divider / emojis come from load-config.sh.
source .ddev/scripts/load-config.sh

# Check for Lefthook (if using git hooks)
LEFTHOOK=$(which lefthook || true)
if [[ "${LEFTHOOK}" == "" ]] && [[ -f ".lefthook.yml" ]]; then
  echo -e "\n${construction} ${yellow} Checking for Lefthook.${NC} ${construction}\n"
  echo -e "If you don't have Lefthook installed, this will ask for your password."
  echo -e "Installing Lefthook."
  ARCH=$(uname -m)
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    sudo curl -fsSL -o /usr/local/bin/lefthook "https://github.com/evilmartians/lefthook/releases/download/v1.5.2/lefthook_1.5.2_MacOS_${ARCH}"
  else
    # Linux
    sudo curl -fsSL -o /usr/local/bin/lefthook "https://github.com/evilmartians/lefthook/releases/download/v1.5.2/lefthook_1.5.2_Linux_${ARCH}"
  fi
  echo -e "Setting Lefthook permissions."
  sudo chmod +x /usr/local/bin/lefthook
  echo -e "${green}${divider}${NC}"
fi

# Initialize Lefthook if config exists
if [[ -f ".lefthook.yml" ]] && [[ "${LEFTHOOK}" != "" ]]; then
  echo -e "\n${construction} ${yellow} Initializing Lefthook.${NC} ${construction}"
  echo -e "This should require no input."
  echo -e "${green}${divider}${NC}"
  lefthook install
fi
