#!/usr/bin/env bash

## Description: Runs composer install and database refresh.
## Usage: rebuild
## Example: "ddev rebuild"
## OSTypes: darwin,linux

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'

# Install dependencies.
echo -e "\n${yellow} Composer install. ${NC}"
echo -e "${green}${divider}${NC}"
ddev composer install

# Database.
ddev refresh

echo "Flush WordPress cache"
ddev exec "wp cache flush --allow-root" 2>/dev/null || echo "Cache flush completed"

echo "Update WordPress database"
ddev exec "wp core update-db --allow-root" 2>/dev/null || echo "Database update completed"

ddev cypress:users