#ddev-generated
# Kanopi WordPress DDEV Configuration
# This file will be copied to .ddev/config.kanopi.yaml during installation

# NOTE: Hosting provider settings (HOSTING_PROVIDER, HOSTING_SITE, etc.) 
# are now configured via environment variables in .ddev/config.yaml
# See install.yaml for hosting provider configuration

# WordPress Admin Configuration
wordpress:
  admin_user: "xxxxxx"
  admin_pass: "xxxxxx"
  admin_email: "xxxxxx"

# Theme Configuration  
theme:
  slug: "struts"
  relative_path: "wp-content/themes/custom/struts"

# Premium Plugin Licenses
licenses:
  acf_client_user: "your-acf-license-key"
  gf_client_user: "your-gravity-forms-license-key"

# Development Settings
development:
  xdebug_enabled: false

# Migration Settings (optional)
migration:
  # source_site: "your-source-site-name"
  # source_env: "live"