#ddev-generated
# Kanopi WordPress DDEV Configuration
# This file will be copied to .ddev/config.kanopi.yaml during installation

# NOTE: All configuration is now handled via environment variables in .ddev/config.yaml
# - HOSTING_PROVIDER, HOSTING_SITE, HOSTING_ENV for platform settings
# - THEME, THEMENAME for theme configuration  
# - MIGRATE_DB_SOURCE, MIGRATE_DB_ENV for migration settings
# See install.yaml for interactive configuration setup

# WordPress Admin Configuration
wordpress:
  admin_user: "xxxxxx"
  admin_pass: "xxxxxx"
  admin_email: "xxxxxx"

# Premium Plugin Licenses
licenses:
  acf_client_user: "your-acf-license-key"
  gf_client_user: "your-gravity-forms-license-key"

# Development Settings
development:
  xdebug_enabled: false