#ddev-generated
# Docker Compose configuration for Kanopi WordPress development environment

version: '3.6'

services:
  # PhpMyAdmin for database management
  pma:
    image: phpmyadmin/phpmyadmin
    restart: "no"
    container_name: ddev-${DDEV_SITENAME}-pma
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=1024M
    ports:
      - "8036"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"

  # Redis for object caching
  redis:
    image: redis:7-alpine
    restart: "no"
    container_name: ddev-${DDEV_SITENAME}-redis
    ports:
      - "6379"
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - redis-data:/data

  # Solr for search (Pantheon-compatible)
  solr:
    image: solr:8-slim
    restart: "no"
    container_name: ddev-${DDEV_SITENAME}-solr
    ports:
      - "8983"
    environment:
      - SOLR_HEAP=1024m
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - solr-data:/var/solr
    command:
      - solr-precreate
      - core1

volumes:
  redis-data:
  solr-data: