version: 2.1

jobs:
  test-ddev-addon:
    machine:
      image: ubuntu-2204:2023.04.2
      resource_class: medium
    working_directory: ~/project
    
    steps:
      - checkout
      
      - run:
          name: Environment setup
          command: |
            # Update package lists
            sudo apt-get update
            
            # Install dependencies
            sudo apt-get install -y git curl
            
            # Install bats-core from GitHub (newer version)
            git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
            cd /tmp/bats-core
            sudo ./install.sh /usr/local
            
            # Install mkcert for local certificates
            curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
            chmod +x mkcert-v*-linux-amd64
            sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
            mkcert -install

      - run:
          name: Install DDEV
          command: |
            # Install DDEV stable version
            curl -fsSL https://ddev.com/install.sh | bash
            # DDEV installs to /usr/local/bin, add it to PATH if not already there
            echo 'export PATH="/usr/local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            ddev version

      - run:
          name: Configure DDEV for testing
          command: |
            # Configure DDEV environment for add-on testing
            mkdir -p ~/.ddev
            echo "instrumentation_opt_in: false" > ~/.ddev/global_config.yaml
            echo "omit_containers: [ddev-ssh-agent]" >> ~/.ddev/global_config.yaml
            echo "use_dns_when_possible: false" >> ~/.ddev/global_config.yaml
            echo "router_bind_all_interfaces: true" >> ~/.ddev/global_config.yaml

            # Set up dummy Terminus token for testing
            echo "web_environment:" >> ~/.ddev/global_config.yaml
            echo "  - TERMINUS_MACHINE_TOKEN=test_token_for_ci" >> ~/.ddev/global_config.yaml

      - run:
          name: Basic DDEV usage test
          command: |
            source $BASH_ENV
            ddev version
            mkdir -p ~/tmp/test-addon-test
            cd ~/tmp/test-addon-test
            ddev config --project-type=php --project-name=test-addon-test
            ddev start
            ddev stop
            ddev delete -Oy

      - run:
          name: Install add-on and run tests
          command: |
            source $BASH_ENV
            export DIR="$(pwd)"
            echo "BATS version:"
            bats --version
            echo "Running tests with DIR=$DIR"
            bats --verbose-run tests/test.bats

workflows:
  version: 2
  test:
    jobs:
      - test-ddev-addon
