name: tests
on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '25 09 * * *'

jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [stable]
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Environment setup
      run: |
        brew install bats-core mkcert
        mkcert -install

    - name: Use ddev stable
      if: matrix.ddev_version == 'stable'
      run: |
        brew install ddev/ddev/ddev
        ddev version

    - name: Use ddev edge
      if: matrix.ddev_version == 'HEAD'
      run: |
        brew install --HEAD ddev/ddev-edge/ddev
        ddev version

    - name: Basic ddev usage
      run: |
        ddev version
        mkdir -p ~/tmp && cd ~/tmp && ddev config --project-type=php --project-name=test-addon-test
        cd ~/tmp/test-addon-test
        ddev start
        ddev stop
        ddev delete -Oy

    - name: Install add-on and test
      run: |
        export DIR="$( cd "$( dirname "$BASH_SOURCE[0]" )" >/dev/null 2>&1 && pwd )/../.."
        cd ~/tmp && git clone https://github.com/ddev/ddev-addon-template.git
        cd ~/tmp/ddev-addon-template
        export DIR="$(pwd)"
        bats tests/test.bats